osx_image: xcode10.2
language: swift
#os: osx
#xcode_project: Numero.xcodeproj
#xcode_scheme: Numero
#xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone 8

script:
- fastlane scan
# blocklist
branches:
  except:
  - Branch2_TestCI

# safelist
branches:
  only:
  - master
